# Generated by Django 4.1.1 on 2023-06-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
